parameters:
    mygento.access_control.config.bundle_dir: '%kernel.project_dir%/vendor/mygento/access-control-bundle'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mygento\AccessControlBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Core/Domain/Entity/'
            - '../src/ACL/Domain/Entity/'

    mygento.access_control.facade:
        class: 'Mygento\AccessControlBundle\Core\Facade'
        public: true

    Mygento\AccessControlBundle\Core\Facade:
        alias: 'mygento.access_control.facade'
