parameters:
    mygento.access_control.config.bundle_dir: '%kernel.project_dir%/vendor/mygento/access-control-bundle'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mygento\AccessControlBundle\:
        resource: '../src/'
        exclude:
            - '../src/AccessControlBundle.php'
            - '../src/DependencyInjection/'
            - '../src/Core/Domain/Entity/'
            - '../src/Core/Domain/ValueObject/'
            - '../src/ACL/Entity/'


    mygento.access_control.facade:
        class: 'Mygento\AccessControlBundle\Core\Domain\Service\AccessControlFacade'
        public: true
        lazy: true

    Mygento\AccessControlBundle\Core\Domain\Service\AccessControlFacade:
        alias: 'mygento.access_control.facade'


    mygento.access_control.security_voter:
        class: 'Mygento\AccessControlBundle\Core\Domain\Service\SecurityVoter'
        bind:
            $accessControlChecker: '@mygento.access_control.access_control_checker'
        public: true

    Mygento\AccessControlBundle\Core\Domain\Service\SecurityVoter:
        alias: 'mygento.access_control.security_voter'


    mygento.access_control.access_control_checker:
        class: 'Mygento\AccessControlBundle\ACL\Repository\ACERepository'
        public: true

    Mygento\AccessControlBundle\Core\Domain\Service\AccessControlCheckerInterface:
        alias: 'mygento.access_control.access_control_checker'


    Mygento\AccessControlBundle\Core\Domain\Service\CustomAccessControlCheckerInterface:
        public: true


    Mygento\AccessControlBundle\ACL\Domain\Service\ACLSynchronizer:
        alias: 'mygento.access_control.acl_synchronizer'

    mygento.access_control.acl_synchronizer:
        class: 'Mygento\AccessControlBundle\ACL\Domain\Service\ACLSynchronizer'
        public: true

    mygento.access_control.doctrine_metadata_listener:
        class: 'Mygento\AccessControlBundle\Core\Listener\DoctrineMetadataListener'
        public: true
