parameters:
    mygento.access_control.config.bundle_dir: '%kernel.project_dir%/vendor/mygento/access-control-bundle'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mygento\AccessControlBundle\:
        resource: '../src/'
        exclude:
            - '../src/AccessControlBundle.php'
            - '../src/DependencyInjection/'
            - '../src/Core/Domain/Entity/'
            - '../src/Core/Domain/ValueObject/'
            - '../src/ACL/Entity/'

    mygento.access_control.manager:
        class: 'Mygento\AccessControlBundle\Core\Domain\Service\AccessControlManager'
        public: true
        lazy: true

    Mygento\AccessControlBundle\Core\Domain\Service\AccessControlManager:
        alias: 'mygento.access_control.manager'

    mygento.access_control.security_voter:
        class: 'Mygento\AccessControlBundle\Core\Domain\Service\SecurityVoter'
        bind:
            $accessControlChecker: '@mygento.access_control.access_control_checker'
        public: true

    Mygento\AccessControlBundle\Core\Domain\Service\SecurityVoter:
        alias: 'mygento.access_control.security_voter'

    mygento.access_control.access_control_checker:
        class: 'Mygento\AccessControlBundle\ACL\Repository\ACERepository'
        public: true

    Mygento\AccessControlBundle\Core\Domain\Service\AccessControlCheckerInterface:
        alias: 'mygento.access_control.access_control_checker'
