version: "3"

services:

    jenkins:
        container_name: probation-jenkins
        image: jenkins/jenkins:latest
        ports:
            - "8090:8080"
            - "50000:50000"
        links:
            - "app"
        volumes:
            - "jenkins:/var/jenkins_home"

    app:
        container_name: probation-app
        build:
            context: ./../app/
        ports:
            - "8091:8080"
        expose:
            - "22"
        volumes:
            - ./../app/:/var/app/
        extra_hosts:
            - host.docker.internal:host-gateway

    database:
        container_name: probation-database
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: password
            POSTGRES_USER: admin
        volumes:
            - db-data:/var/lib/postgresql/data:rw

    memcached:
        container_name: probation-memcached
        image: memcached:1.6-alpine

    redis:
        container_name: probation-redis
        image: redis:6-alpine

    rabbitmq:
        container_name: probation-rabbitmq
        image: rabbitmq:3.9-management-alpine
        ports:
            - "15672"

volumes:
    jenkins:
    db-data:
