framework:
    messenger:
        failure_transport: sync

        transports:
            rabbitmq:
                dsn: '%env(resolve:RABBITMQ_DSN)%'

            sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: rabbitmq
            Symfony\Component\Notifier\Message\ChatMessage: rabbitmq
            Symfony\Component\Notifier\Message\SmsMessage: rabbitmq

            'App\Message\OrderConfirmationEmail': rabbitmq
