doctrine:
    orm:
        mappings:

            AccessControlBundle\Core:
                type: annotation
                dir: '%mygento.access_control.config.bundle_dir%/src/Core/Domain/Entity'
                prefix: 'Mygento\AccessControlBundle\Core\Domain\Entity'
                alias: AccessControlBundle\Core

            AccessControlBundle\ACL:
                type: annotation
                dir: '%mygento.access_control.config.bundle_dir%/src/ACL/Domain/Entity'
                prefix: 'Mygento\AccessControlBundle\ACL\Domain\Entity'
                alias: AccessControlBundle\ACL
